using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Kitty {
    class KittyHighCobra:KittyPL {

        public KittyHighCobra() {
            Language = "Cobra";
            Langs["cobra"] = this;
            KeyWords.Add("abstract");
            KeyWords.Add("adds");
            KeyWords.Add("all");
            KeyWords.Add("and");
            KeyWords.Add("any");
            KeyWords.Add("as");
            KeyWords.Add("assert");
            KeyWords.Add("base");
            KeyWords.Add("be");
            KeyWords.Add("body");
            KeyWords.Add("bool");
            KeyWords.Add("branch");
            KeyWords.Add("break");
            KeyWords.Add("callable");
            KeyWords.Add("catch");
            KeyWords.Add("char");
            KeyWords.Add("class");
            KeyWords.Add("const");
            KeyWords.Add("continue");
            KeyWords.Add("cue");
            KeyWords.Add("decimal");
            KeyWords.Add("def");
            KeyWords.Add("do");
            KeyWords.Add("dynamic");
            KeyWords.Add("each");
            KeyWords.Add("else");
            KeyWords.Add("end");
            KeyWords.Add("ensure");
            KeyWords.Add("enum");
            KeyWords.Add("event");
            KeyWords.Add("every");
            KeyWords.Add("except");
            KeyWords.Add("expect");
            KeyWords.Add("extend");
            KeyWords.Add("extern");
            KeyWords.Add("fake");
            KeyWords.Add("false");
            KeyWords.Add("finally");
            KeyWords.Add("float");
            KeyWords.Add("for");
            KeyWords.Add("from");
            KeyWords.Add("get");
            KeyWords.Add("has");
            KeyWords.Add("if");
            KeyWords.Add("ignore");
            KeyWords.Add("implements");
            KeyWords.Add("implies");
            KeyWords.Add("import");
            KeyWords.Add("in");
            KeyWords.Add("inherits");
            KeyWords.Add("inlined");
            KeyWords.Add("inout");
            KeyWords.Add("int");
            KeyWords.Add("interface");
            KeyWords.Add("internal");
            KeyWords.Add("invariant");
            KeyWords.Add("is");
            KeyWords.Add("listen");
            KeyWords.Add("lock");
            KeyWords.Add("mixin");
            KeyWords.Add("must");
            KeyWords.Add("namespace");
            KeyWords.Add("new");
            KeyWords.Add("nil");
            KeyWords.Add("nonvirtual");
            KeyWords.Add("not");
            KeyWords.Add("number");
            KeyWords.Add("objc");
            KeyWords.Add("of");
            KeyWords.Add("off");
            KeyWords.Add("old");
            KeyWords.Add("on");
            KeyWords.Add("or");
            KeyWords.Add("out");
            KeyWords.Add("override");
            KeyWords.Add("par");
            KeyWords.Add("partial");
            KeyWords.Add("pass");
            KeyWords.Add("passthrough");
            KeyWords.Add("post");
            KeyWords.Add("print");
            KeyWords.Add("private");
            KeyWords.Add("pro");
            KeyWords.Add("protected");
            KeyWords.Add("public");
            KeyWords.Add("raise");
            KeyWords.Add("ref");
            KeyWords.Add("require");
            KeyWords.Add("return");
            KeyWords.Add("same");
            KeyWords.Add("set");
            KeyWords.Add("shared");
            KeyWords.Add("sig");
            KeyWords.Add("stop");
            KeyWords.Add("struct");
            KeyWords.Add("success");
            KeyWords.Add("test");
            KeyWords.Add("this");
            KeyWords.Add("throw");
            KeyWords.Add("to");
            KeyWords.Add("to?");
            KeyWords.Add("trace");
            KeyWords.Add("true");
            KeyWords.Add("try");
            KeyWords.Add("uint");
            KeyWords.Add("use");
            KeyWords.Add("using");
            KeyWords.Add("var");
            KeyWords.Add("vari");
            KeyWords.Add("virtual");
            KeyWords.Add("where");
            KeyWords.Add("while");
            KeyWords.Add("yield");
    }

    }
}
